spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/redis
        username: sa
        password:
        driver-class-name: org.h2.Driver

    redis:
        host: 127.0.0.1
        port: 6379

    jpa:
        hibernate:
            ddl-auto: none # application loading 시점 table drop 실행
        properties:
            hibernate:
            # show_sql: true
            format_sql: true

logging.level:
    org.hibernate.SQL: debug
    # org.hibernate.type: trace
